version: '3.4'

services:
  sentimentanalysisofsocialmediawebsite:
    image: sentimentanalysisofsocialmediawebsite
    ports:
       - '80:80'
    build:
      context: .
      dockerfile: ./Dockerfile
